### ISSUE TITLE
install.sh: Declaration of WALLPAPER_DIR missing

### ISSUE THREAD

**Issue by fhemberger** [vinceliuice/Layan-kde#1]
The installer script [references the variable WALLPAPER_DIR](https://github.com/vinceliuice/Layan-kde/blob/master/install.sh#L31) without declaring it first. So it tries to install the wallpaper into `/Matcha`, which of course fails.

I think you want to define `WALLPAPER_DIR` like:
```
WALLPAPER_DIR="$HOME/Pictures"
```

**Comment by vinceliuice** [comment]
Fixed
