### ISSUE TITLE
Minimized Application appearance

### ISSUE THREAD

**Issue by esmacdon** [vinceliuice/Layan-kde#10]
Hi, I'm not able to distinguish between what apps are not open and which apps are minimized.  Is there something I can configure to change this?
![image](https://user-images.githubusercontent.com/59851891/77498442-06326500-6e26-11ea-836f-73df7a0f04ae.png)
(the application rightmost is minimized, for example. not closed.)

Other than this, very very nice theme!  This is honestly the only issue I have with it.

**Comment by vinceliuice** [comment]
I'll fix this!

**Comment by esmacdon** [comment]
hey!!  thank you so much for the update!
