### ISSUE TITLE
System wide installation

### ISSUE THREAD

**Issue by ShayBox** [vinceliuice/Layan-kde#2]
Your gtk theme supports both system and user paths, kde has similar paths for system wide installation

**Comment by vinceliuice** [comment]
Aurorae don't have sysytem theme path

**Comment by ShayBox** [comment]
It does
![image](https://user-images.githubusercontent.com/9505196/72962994-f1811480-3d83-11ea-86a1-e95c8788d523.png)

**Comment by vinceliuice** [comment]
Get it, thank you, now I updated the install script.

**Comment by ShayBox** [comment]
Forgot to delete $HOME, otherwise👍

**Comment by vinceliuice** [comment]
Oh! thanks, didn't notice that, now it's all OK.
