### ISSUE TITLE
Tooltips white background with white text on Layan plasma style

### ISSUE THREAD

**Issue by NabeelUppel** [vinceliuice/Layan-kde#33]
Hi, I recently installed this theme on my pc and was having some issues with the tooltip colours when you hover on icons in the taskbar on the layan  plasma style. Is there any way to change it? I managed to change the text color by changing BackgroundNormal under windows in the colors file but that effects the color of the icons on the taskbar as well. Any help would be appreciated.

![tool](https://user-images.githubusercontent.com/52805376/153924127-a9ef5008-b646-4319-84b7-46d5f732f820.png)
.

**Comment by snacksncode** [comment]
I also have the same problem with systray tooltips (https://i.imgur.com/KmhenVi.png)

**Comment by muzhawir** [comment]
I also had the same problem with the tooltip. (https://imgur.com/a/OIM59S0)

**Comment by abhiroop43** [comment]
![image](https://user-images.githubusercontent.com/5673129/157519872-df68f306-457a-4264-aa20-6f6c8c675379.png)

yes, the same issue with me as well
