### ISSUE TITLE
Unreadable tooltip/preview colors when hover over items in Plasma panel

### ISSUE THREAD

**Issue by akza07** [vinceliuice/Layan-kde#36]
![image](https://user-images.githubusercontent.com/30655539/157604783-89993f62-762f-4ec4-8d05-02b3a93c5121.png)

I don't know if this is an issue with my installation. All themes and kvantum themes are set to Layan. Only the Plasma Panel is having this issue. Other tool tips are dark and readable.

**Comment by vinceliuice** [comment]
Fixed now

**Comment by akza07** [comment]
Thank you. Just pulled latest changes. It's fixed.
