### ISSUE TITLE
Window decoration blur is broken

### ISSUE THREAD

**Issue by Rayrsn** [vinceliuice/Layan-kde#43]
![blur](https://user-images.githubusercontent.com/25773909/174459055-d367a1ed-edc5-43e5-81b1-29049620cad8.png)
Window decoration is transparent instead of being blurry.

**Comment by HerrCraziDev** [comment]
Same here. This appears to be the same problem as in #44, most likely related to the Kwin 5.25 update changing stuff with window decorations.
