### ISSUE TITLE
Hard to see Bluetooth icon when is small or big 

### ISSUE THREAD

**Issue by vel-er** [vinceliuice/Layan-kde#47]
The icons for Bluetooth in the system tray (`Image path: icons/preferences`) is hard to see when a device is connected (with the small blue dot above), in normal/regular size everything is okay, but when you change the size of the panel to 20 px or 46 px and above (in my 1080p display) the icon turns black, which should be white, according to the uniformity of the theme.

![image](https://user-images.githubusercontent.com/56132129/184276567-5bdc4a65-f9ae-4259-9488-431ef3a5c9ee.png)

Operating System: Arch Linux
KDE Plasma Version: 5.25.4
KDE Frameworks Version: 5.96.0
Qt Version: 5.15.5
Kernel Version: 5.18.16-arch1-1 (64-bit)
Graphics Platform: X11

**Comment by vinceliuice** [comment]
Fixed
