### ISSUE TITLE
Plasma theme forces minimum panel size of 32px on KDE 5.27

### ISSUE THREAD

**Issue by tatsumara** [vinceliuice/Layan-kde#53]
starting with the recent update to 5.27, this theme forces my top panel (and probably others) to be at least 32 pixels high/wide. before 5.27, i was able to scale panels down to 28 pixels, which looked a lot better. switching to the default breeze theme allows me to go back down to 28, but this gets reset back to 32 when i switch back to layan.

**Comment by Wind134** [comment]
me too!

**Comment by vel-er** [comment]
Yes, please allow down to 20 px.

**Comment by AI-ien** [comment]
I think it's plasma related issue not theme. Also I'm on plasma version 5.27.4 and I can set it to 28px.

**Comment by vinceliuice** [comment]
Now on the last plasma the panel height size is set to double panel border-radius size，so I can set set the panel border-radius to 10px, then it can be down to 20px
