### ISSUE TITLE
What's the transparency value for this theme?

### ISSUE THREAD

**Issue by MonstrousOgre** [vinceliuice/Layan-kde#56]
So I'm trying to get my kitty config to match this theme. By looking at the code, I've managed to figure out that the window color for the LayanDark is #31313A, but I just can't figure out what the transparency percentage is.

I've fooled around with many opacity values in kitty and none of them seem to match. The title bar is always more or less opaque than the terminal window.

**Comment by MonstrousOgre** [comment]
Nevermind. I looked in the svg and found it

**Comment by rastiqdev** [comment]
What was it? I can't manage to find it...

**Comment by rastiqdev** [comment]
Found it, it's `0.8`. Nevertheless it isn't matching with the window color...
