### ISSUE TITLE
Feature request: port to Plasma 6

### ISSUE THREAD

**Issue by fxzjshm** [vinceliuice/Layan-kde#59]
Firstly, thanks for your awesome works!

In Plasma 6, they seem to have dropped support for metadata.desktop files and use metadata.json instead, so need to use `desktoptojson` to convert, like
```bash
find -name "*.desktop" -exec desktoptojson -i {} \;
```
furthermore manual edit is needed, e.g. for `plasma/look-and-feel/*/metadata.json`,
```diff
  {
+     "KPackageStructure": "Plasma/LookAndFeel",
      "KPlugin": {
          "Authors": [
              { 
```
Hope this helps.

**Comment by sesu-tech** [comment]
+1, just upgraded to Plasma 6.0 and disappointed to be missing my layan D:

I'll contribute a monetary donation for the port of this :)

**Comment by davigamer987** [comment]
+1 on this, Arch updated to Plasma 6 today

**Comment by shadmansaleh** [comment]
+1, really enjoy the theme. would love to use it on plasma 6 too

**Comment by SirCanucklehead** [comment]
+1. Has been my default theme since switching to KDE a few years ago. Would love to carry it over to the new release.

**Comment by mashletov** [comment]
+1. This is the only KDE theme I like. I'm looking forward to the port.

**Comment by DarkXero-dev** [comment]
+1 Been using this theme for 3 years not gonna use anything else.. I too await full port to Plasma 6 ..

**Comment by hyknn** [comment]
+1

**Comment by DarkXero-dev** [comment]
Seems to be working after applying OP's "fix"
![image](https://github.com/vinceliuice/Layan-kde/assets/81101439/1977d63f-bc27-4254-8030-a4298f832ea5)

**Comment by Tecnio** [comment]
It would be great if someone who has fixed the theme could create a merge request.

**Comment by DarkXero-dev** [comment]
There are still issues with mouse context menus not always appearing .. It's a theme issue that needs to be addressed coz on Breeze it ain't there.. It's not yet fully fixed.. Needs some love from the man, the myth the legend @vinceliuice

**Comment by DarkXero-dev** [comment]
After Kvantum got updated all is working great. All that is missing are the json files for theme to show under Global themes. I have no clue how to do an MR if anyone here can please do coz that's all that this awesome theme is missing...

Cheers...

**Comment by Redhawk18** [comment]
+1

**Comment by DarkXero-dev** [comment]
Seems not matter how many ++++ we give @vinceliuice will get to it when he has time for now it's dead Jim...

**Comment by davigamer987** [comment]
Anyone's tried the PR that adds Plasma 6 support?

**Comment by CJFxTiKiMoN** [comment]
> Anyone's tried the PR that adds Plasma 6 support?

Yup, just installed Layan from Master via `install.sh` and everything is working flawlessly.
![Screenshot_20240521_214354](https://github.com/vinceliuice/Layan-kde/assets/52645623/36b813f1-b804-4413-8ed0-3f153809c67f)

**Comment by vinceliuice** [comment]
Fixed
