### ISSUE TITLE
Notifications white ¨Baby Corner Guards¨

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [vinceliuice/Layan-kde#6]
![](https://i.imgur.com/jslYkph.png)
As you can see on these screenshots, Notifications pop-ups and tray pop-ups have a some weird white angles artifacts (That I call Corner Guards, those little protections we put on table and stuff, to restrain small children to bump into it)

**Comment by PoorPocketsMcNewHold** [comment]
![Peek 17-02-2020 10-01](https://user-images.githubusercontent.com/13170204/74638583-1048b000-5164-11ea-9561-deea5cd51a96.gif)
Strangely, this seems to happen, only behind white areas (And by areas, even small portions of white on my desktop plasmoids work)

**Comment by vinceliuice** [comment]
Thanks, I'll fix this

**Comment by vinceliuice** [comment]
I update the tooltip svg file, you can try again

**Comment by PoorPocketsMcNewHold** [comment]
![Peek 17-02-2020 09-35](https://user-images.githubusercontent.com/13170204/74722142-58cd9f80-5230-11ea-8d01-a464f8ffd9b9.gif)
```[pm@VIX ~]$ cd Layan-kde/
[pm@VIX Layan-kde]$ git pull
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 21 (delta 10), reused 21 (delta 10), pack-reused 0
Dépaquetage des objets: 100% (21/21), 378.96 Kio | 965.00 Kio/s, fait.
Depuis https://github.com/vinceliuice/Layan-kde
7742419..f7f205f  master     -> origin/master
Mise à jour 7742419..f7f205f
Fast-forward
plasma/desktoptheme/Layan/widgets/tooltip.svg                       | 164 +++++++++++++++++++++++++++++++++++++++++++++++---------------------------------------------------------------------------------------------------------------------
plasma/look-and-feel/com.github.vinceliuice.Layan/contents/defaults |   2 +-
plasma/look-and-feel/com.github.vinceliuice.Layan/metadata.desktop  |   2 +-
sddm/themes/Layan/preview.png                                       | Bin 418672 -> 406640 bytes
4 files changed, 49 insertions(+), 119 deletions(-)
[pm@VIX Layan-kde]$ ./install.sh
Installing 'Layan kde themes'...
Install finished...```

**Comment by PoorPocketsMcNewHold** [comment]
Did recently a fresh Arch Installation and tested it straight from the repo. I can confirm you it has been fixed.
Currently reverting to Septor OS instead, so I'll try to give you a preview of this issue being fixed. You can close it already if you want.

**Comment by vinceliuice** [comment]
OK!
