### ISSUE TITLE
[BUG] 使用Kvantum主题时qBittorrent和telegram出现的问题

### ISSUE THREAD

**Issue by LockRim** [vinceliuice/Layan-kde#64]
如题，鼠标双击才能点中一个文件
同时发现鼠标左键长按拖动时，整个文件框在移动而不是多选文件
状态和分类菜单会出现透明的情况
在telegram同时发现很多选项需要双击才能点开的情况

> 使用layan主题时

https://github.com/user-attachments/assets/944040ea-3b8a-41db-871c-8b21a448febb

> 使用whiteSur时

https://github.com/user-attachments/assets/4777eef4-78d5-4773-834c-91758aa4e2ce

**Comment by vinceliuice** [comment]
视频损害了

**Comment by LockRim** [comment]
> 视频损坏了

更新了一下，现在可以了吗

**Comment by vinceliuice** [comment]
还是看不了

**Comment by LockRim** [comment]
> 还是看不了

https://pan.baidu.com/s/1sdVaDuWaRx0bqXwetnqdRA?pwd=f274
