### ISSUE TITLE
Can't download window decorations

### ISSUE THREAD

**Issue by danee940** [vinceliuice/Layan-kde#65]
If I try to download from here: https://store.kde.org/p/1325238

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<response>
<status>error</status>
<message>file not found (id: Zt4M1q-rpM0xdVDBQzkZ9QABF)</message>
</response>

It also doesn't appear if I search in Download New Window Decorations in KDE

**Comment by vinceliuice** [comment]
I don't know what's going on, but I update it, wish it gona work

**Comment by danee940** [comment]
Mm, still not working. Neither from the website.

![Screenshot_20240909_092547](https://github.com/user-attachments/assets/af937e9f-3bc1-43c0-a9f4-d3ede2e79c2c)

**Comment by vinceliuice** [comment]
Well, this is not a theme issue, you can try search other themes, only Layan not show ?

**Comment by danee940** [comment]
Yes, other themes are fine.

And this is what shows up if I try to download the zipped file from the website.

![image](https://github.com/user-attachments/assets/34606af5-db36-423c-944d-62aa816bac05)

**Comment by vinceliuice** [comment]
What about now ?

**Comment by danee940** [comment]
![image](https://github.com/user-attachments/assets/7fe0d724-efeb-4ed3-b566-215b07c2ccae)

It now shows up in the search, but when I try to download it gives me this error.
The web download gives the same "XML file does not appear (...)" error.

**Comment by vinceliuice** [comment]
I updated the xml file, what about now ?

**Comment by danee940** [comment]
It works now! Both from KDE, and both from the website.
