### ISSUE TITLE
Round corners

### ISSUE THREAD

**Issue by squidink7** [vinceliuice/Layan-kde#9]
Now that KDE 5.18 has been released, it has round corners on almost everything. I was wondering if there was a way to round the window borders and tooltips, etc. without using the system transparency which becomes ruined once you turn on blur/disable transparency in settings.

**Comment by vinceliuice** [comment]
You can turn off the transparency on setting

**Comment by squidink7** [comment]
I know, but it makes the corners have the black effect from another issue. I was just wondering if there was another way to make the corners round. If not I will close this issue.

**Comment by vinceliuice** [comment]
I don't know what else can make corners round and don't have blurring issues, this seems a kwin bug

**Comment by squidink7** [comment]
ok, thanks anyway. I have made a bug report on bugs.kde.org so hopefully they will fix it.
